= noterc(5)
:doctype:    manpage
:man source: pynote

== Name

noterc - runtime configuration for pynote

== Synopsis

----
/etc/xdg/noterc
$XDG_CONFIG_HOME/note/noterc
$HOME/.config/note/noterc
----

== Description

Pynote is configured with a local and a global ressource file. The local
ressource file can be used to overwrite values from the global one; Pynote uses
the XDG Base Directory Specification. If the environment variable
`XDG_CONFIG_HOME` is set, pynote searches the local config file in
`$XDG_CONFIG_HOME/note/noterc`. If the variable is unset pynote looks into
`$HOME/.config/note/noterc`.

Each file is formatted as a line-separated list of `KEY=VALUE` pairs, blank
lines, and lines starting with `#`, are ignored.

== Sections

Pynote's configuration is devided into several sections. A section starts with
the section name in square brackets, e.g. `[ui]`. More information about
python's configparser can be found in the official python documentation.

=== [data]

path [default: `$HOME/.local/share/note`]::
    Specifies the place where stored notes live. `~` is expanded to the homedir
    of the current user. This location can be set to,  e.g. a Syncthing
    directory to ensure automatic synchronization of notes. This value defaults
    to `$XDG_DATA_HOME/note`, which falls back to `$HOME/.local/share/note`.

extension [default: `.txt`]::
    Specifies an extension that will be added to the filename of each note.
    This might be useful for using markup languages (such as rst, asciidoc,
    markdown...) and syntax highlighting in your editor. The dot has to be
    included.

ignore [default: `GIT`]::
    Ignore files in the notes folder with a specific extension, e.g. `.pdf`.
    It may be useful if other files are stored in the datadir, such as pdfs.
    This configuration value must be a comma separated string. Since pynote
    2.1.0 there is the special value `GIT` available, which is the new default.
    `GIT` means that `git ls-files` is used, to populate the note table. The
    benefit of this approach is, that the `.gitignore` file can be used to
    define ignore patterns in `data.path`.

tmpfile [default: `no`]::
    Use a tmpfile when editing notes. The note file will not be edited
    directly. After successfully finished editing the tmpfile is copied to the
    note's location.

slugify [default: `no`]::
    This option enables slugified filenames and thus slugified titles. Slugify
    normalizes UTF-8 strings, removes any whitespace characters and replaces
    them with dashes.

=== [ui]

dateformat [default: `YYYY-MM-dd HH:mm`]::
    Sets the default dateformat for all dates shown in pynote. A list with all
    available config values can be obtained from the arrow documentation:
    https://github.com/crsmithdev/arrow/blob/master/docs/index.rst#tokens

reldates [default: `yes`]::
    Use relative dates in, for instance `note list` and `note show`. Internally
    the library `arrow` is used to generate reldates.

editor [default: `${EDITOR:-vi}`]::
    The command line editor which is used to create and edit notes.  Additional
    arguments can be passed to the editor as well, e.g.  `nvim -c "set
    ft=asciidoc"`. If it is not present pynote will take the value of the
    environment variable `$EDITOR``. If `$EDITOR` is not set, this value will
    fall back to `'vi'`.

pager [default: `${PAGER:-less}`]::
    Configure the pager used by `note(1)`. If this value is not set, it reads the
    environment variable `PAGER`; otherwise it defaults to `less`. If the chosen
    pager is `less` and the environment variable `LESS` is not set, `note(1)`
    sets it to `FRX`; this behaviour has been prodly stolen from `git`.

style [default: `simple`]::
    There is more than one way to format a table in plain text. These styles
    are provided by the `tabulate` library. Supported table formats are:

    * `plain`
    * `simple`
    * `grid`
    * `fancy_grid`
    * `pipe`
    * `orgtbl`
    * `jira`
    * `psql`
    * `rst`
    * `mediawiki`
    * `moinmoin`
    * `html`
    * `latex`
    * `latex_booktabs`
    * `textile`

=== [aliases]

Each subcommand of `note(1)` can be aliased with a configurable string. In this
section an alias can be assigned to a command like this:

    command = alias

Multiple aliases are allowed by assigning a comma separated list:

    command = alias1, alias2

A real world example can be found in the "Example File" section below.

=== [git]

enabled [default: `yes`]::
    Enables git support. Every time a note is changed, a `git commit` is filed.
    This enables merging and syncing notes effectively with git. Please note,
    that `data.path` must point to a git repository and git must be properly
    configured in the first place. A git repository can created with `note(1)`
    as well using: `note "git init"`

suppress_output [default: `no`]::
    The output of git is not suppressed by default. Some people may find this
    annoying. Setting this option to `yes` redirects any output of git to
    `/dev/null`.

=== [grep]

backend [default: `grep`]::
    Backend that will be used in `note grep`. Sane backends are: `git-grep`, 
    `ag`, `pt`. The default is `grep`.

flags [default: `-r`; for backend `grep`, `''` otherwise]::
    Flags, that are passed to `grep.backend`. If both, `grep.backend` and 
    `grep.flags` are unset, this value defaults to `-f`. Otherwise it is
    an empty string.

== Example File

----
[data]
path = ~/Sync/Notes
extension = .txt
slugify = no
ignore_extensions = .pdf, .odt

[ui]
editor = nvim -c "set ft=asciidoc"
reldates = yes
style = psql

[aliases]
add = a, new, n
list = l
edit = e
show = s

[git]
enabled = yes

[grep]
backend = ag
flags = -C
----

== See Also

`note(1)`

include::footer.adoc[]
