= noterc(5)
:doctype:    manpage
:man source: pynote

== Name

noterc - runtime configuration for pynote

== Synopsis

----
/etc/xdg/noterc 
$XDG_CONFIG_HOME/note/noterc
$HOME/.config/note/noterc
----

== Description

Pynote is configured with a local and a global ressource file. The local
ressource file can be used to overwrite values from the global one; Pynote uses
the XDG Base Directory Specification. If the environment variable
`XDG_CONFIG_HOME` is set, pynote searches the local config file in
`$XDG_CONFIG_HOME/note/noterc`. If the variable is unset pynote looks into
`$HOME/.config/note/noterc`.

Each file is formatted as a line-separated list of `KEY=VALUE` pairs, blank
lines, and lines starting with `#`, are ignored. 

== Sections

Pynote's configuration is devided into several sections. A section starts with
the section name in square brackets, e.g. `[ui]`. More information about 
python's configparser can be found in the official python documentation.

=== `[ui]`

dateformat [default: `YYYY-MM-dd HH:mm`]::
    Sets the default dateformat for all dates shown in pynote. A list with all
    available config values can be obtained from the arrow documentation:
    https://github.com/crsmithdev/arrow/blob/master/docs/index.rst#tokens

reldates [default: `no`]::
    Use relative dates in, for instance `note list` and `note show`.

editor [default: `${EDITOR:-vi}`]::
    The command line editor which is used to create and edit notes.  Additional
    arguments can be passed to the editor as well, e.g.  `nvim -c "set
    ft=asciidoc"`. If it is not present pynote will take the value of the
    environment variable `$EDITOR``. If `$EDITOR` is not set, this value will
    fall back to `'vi'`.

pager [default: `less`]::
    TODO

=== `[data]` 

path [default: `$HOME/.local/share/note`]::
    Specifies the place where stored notes live. `~` is expanded to the homedir
    of the current user. This location can be set to,  e.g. a Syncthing
    directory to ensure automatic synchronization of notes. This value defaults
    to `$XDG_DATA_HOME/note`, which falls back to `$HOME/.local/share/note`.

extension [default: `.txt`]::
    Specifies an extension that will be added to the filename of each note.
    This might be useful for using markup languages (such as rst, asciidoc,
    markdown...) and synthax highlighting in your editor. The dot has to be
    included.

ignore_extensions [default: `''`]::
    Ignore files in the notes folder with a specific extension, e.g. `.pdf`.
    It may be useful if other files are stored in the datadir, such as pdfs.
    This configuration value must be a comma separated string.

tmpfile [default: `no`]::
    Use a tmpfile when editing notes. The note file will not be edited
    directly. After successfully finished editing the tmpfile is copied to the
    note's location.

slugify_titles [default: `no`]::
    TODO

=== `[aliases]`

TODO

=== `[git]` 

enabled [default: `no`]::
    TODO

suppress_output [default: `no`]::
    TODO

== Example File

----
[ui]
editor = nvim -c "set ft=asciidoc"
reldates = yes

[data]
path = ~/Sync/Notes
extension = .txt
slugify_titles = no
ignore_extensions = .pdf, .odt

[aliases]
add = a, new, n
list = l
edit = e
show = s
----
