#!/usr/bin/env python

import os
import os.path


def main():
    noterc_tpl = ('[paths]\n'
                  'data = ~/.note/data.json\n'
                  'trash = ~/.note/trash.json\n'
                  'versions = ~/.note/versions.json\n'
                  '\n'
                  '[misc]\n'
                  'editor = nano\n')

    noterc_path = os.path.expanduser('~/.noterc')

    if not os.path.exists(noterc_path):
        with open(noterc_path, 'w') as f:
            f.write(noterc_tpl)
    else:
        print("'~/.noterc' already exists.")


if __name__ == '__main__':
    main()
