#!/usr/bin/env python

import sys
import pynote.__main__


if sys.version_info[0] < 3:
    print('ERROR: RUNNING PY2K INSTEAD OF PY3K.')
    print()
    print('If you replaced /usr/bin/python with python2, you are an idiot.')
    print('Please revert that change!')
    exit(1)
else:
    pynote.__main__.run()
