#!/usr/bin/env python

import argparse

from note import Note
from note import TableReport
from note import new_note
from note import show_note
from note import delete_note


def parse_args():
    parser = argparse.ArgumentParser()
    subparser = parser.add_subparsers(dest='cmd',
                                      help='sub-command help')

    parser_add = subparser.add_parser('list')
    # parser_add.add_argument('note', type=str, help='bar help')

    parser_add = subparser.add_parser('new')
    parser_add.add_argument('title', type=str)

    parser_add = subparser.add_parser('show')
    parser_add.add_argument('key', type=str)

    parser_delete = subparser.add_parser('delete')
    parser_delete.add_argument('key', type=str, help='bar help')
    args = parser.parse_args()

    return(args)


def main():
    args = parse_args()

    if args.cmd == 'list':
        print(TableReport())
    elif args.cmd == 'new':
        new_note(args.title)
    elif args.cmd == 'delete':
        delete_note(args.key)
    elif args.cmd == 'show':
        show_note(args.key)


if __name__ == '__main__':
    main()
