= pynote

pynote is a project to manage your notes on the commandline. It is written in
Python 3 and provides a very handy cmd-interface. If something does not behave
as expected please file a bug on https://github.com/rumpelsepp/pynote[Github],
write an mailto:rumpelsepp@sevenbyte.org[email] or check out the
https://bbs.archlinux.org/viewtopic.php?pid=1362268[support thread] in the Arch
Linux forums.

== Install

In Arch Linux you can use the PKGBUILD in the
https://aur.archlinux.org/packages/pynote/[AUR]. Otherwise use `pip` or your
distros package manager (currently it is only in Fedora):

    $ pip install [--user] pynote

On Arch Linux `pacaur` can be used to obatain the AUR package:

    $ pacaur -S pynote

== Requirements

If you plan to do some development for pynote, please make sure that these 
libraries are available:

* https://github.com/crsmithdev/arrow[arrow]
* https://bitbucket.org/astanin/python-tabulate[tabulate]

The minimum required python version is 3.5. Python 2 is not supported.

== Quickstart

For initialization just run any command and pynote will tell you what to do:

----
$ note add "spam"
Path /home/stefan/.local/share/note does not exist
Should I create it?
[y/N] y
Data directory /home/stefan/.local/share/note created
You have enabled git support.
Should I Initialize the repository?
[y/N] y
Initialized empty Git repository in /home/stefan/.local/share/note/.git/

$ note add "spam"
[master (root-commit) fd90645] Note added
 1 file changed, 1 insertion(+)
 create mode 100644 spam.txt
----

Create a new note:

----
$ note add "spam"
----

List notes in a table:

----
$ note 
ID  Title         Age
--  -----------   ---------
0   spam          3 seconds
1   lovely spam   1 day
----

Read a note (use ID from the table or the beginning of the title):

----
$ note show spam
spam @ 2014-05-31 17:19, 48 seconds ago

Spam, Spam, Spam, lovely Spam
Wonderful Spam, Lovely Spam.
Spam, Spam, Spam, magnificent Spam,
Superlative Spam.
Spam, Spam, Spam, wonderous Spam,
Surgical Spam, splendiferous Spam.
Spam, Spam, Spam, Spaaam!
----

Edit a note:

----
$ note edit 0
$ note edit --title 0
----

Use git (make sure it is enabled in `noterc(5)`):

----
$ note git "log -p"
commit 0306372fb810f3a6da7432b3668b5d6471a4491b (HEAD -> master)
Author: Stefan Tatschner <rumpelsepp@sevenbyte.org>
Date:   Thu May 19 23:07:58 2016 +0200

    Note added

diff --git a/todolist.txt b/todolist.txt
new file mode 100644
index 0000000..b586074
--- /dev/null
+++ b/todolist.txt
@@ -0,0 +1 @@
+spam
----

Search all notes (several backends supported, `ag -C` is used here):

----
$ note grep spam
spam.txt
1:Spam, Spam, Spam, lovely Spam
2:Wonderful Spam, Lovely Spam.
3:Spam, Spam, Spam, magnificent Spam,
4:Superlative Spam.
5:Spam, Spam, Spam, wonderous Spam,
6:Surgical Spam, splendiferous Spam.
7:Spam, Spam, Spam, Spaaam!
8-
----

For help just pass `-h` or `--help` to any command, or try `man 1 note` 
and `man 5 noterc`.
